name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_extensions: zip, json, openssl

      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
          path: src/
          memory_limit: 256M
